import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!
)

/**
 * One-time migration: Import all hardcoded model name mappings from
 * fetch-artificial-analysis.ts, fetch-epoch.ts, and fetch-benchmarks.ts
 * into the DB model_name_mappings table.
 */

// From fetch-artificial-analysis.ts: AA_MODEL_MAP
const AA_MAPPINGS: Record<string, string> = {
  'claude-opus-4-6': 'claude-opus-46',
  'claude-opus-4-6-adaptive': 'claude-opus-46',
  'claude-opus-4-5': 'claude-opus-45',
  'claude-4-1-opus': 'claude-opus-41',
  'claude-4-opus': 'claude-opus-4',
  'claude-4-5-sonnet': 'claude-sonnet-45',
  'claude-4-6-sonnet': 'claude-sonnet-46',
  'claude-4-sonnet': 'claude-sonnet-4',
  'claude-4-5-haiku': 'claude-haiku-45',
  'claude-3-7-sonnet': 'claude-37-sonnet',
  'claude-35-sonnet': 'claude-35-sonnet',
  'claude-3-5-haiku': 'claude-35-haiku',
  'gpt-5-2': 'gpt-52',
  'gpt-5': 'gpt-5',
  'gpt-5-1': 'gpt-51',
  'gpt-5-codex': 'gpt-5-codex',
  'gpt-5-2-codex': 'gpt-52-codex',
  'gpt-5-1-codex': 'gpt-51-codex',
  'gpt-5-1-codex-mini': 'gpt-51-codex-mini',
  'gpt-5-1-codex-max': 'gpt-51-codex-max',
  'gpt-4-1': 'gpt-41',
  'gpt-4-1-mini': 'gpt-41-mini',
  'gpt-4-1-nano': 'gpt-41-nano',
  'gpt-4o': 'gpt-4o',
  'gpt-4o-mini': 'gpt-4o-mini',
  'gpt-4-5': 'gpt-45',
  'gpt-5-mini': 'gpt-5-mini',
  'gpt-5-nano': 'gpt-5-nano',
  'gpt-5-pro': 'gpt-5-pro',
  'o3': 'o3',
  'o3-mini': 'o3-mini',
  'o3-pro': 'o3-pro',
  'o4-mini': 'o4-mini',
  'o1': 'o1',
  'o1-mini': 'o1-mini',
  'o1-preview': 'o1-preview',
  'deepseek-r1': 'deepseek-r1',
  'deepseek-r1-0528': 'deepseek-r1-may-2025',
  'deepseek-v3': 'deepseek-v3',
  'deepseek-v3-1': 'deepseek-v31',
  'deepseek-v3-2': 'deepseek-v32',
  'deepseek-v3-2-speciale': 'deepseek-v32-speciale',
  'deepseek-v3-2-exp': 'deepseek-v32-exp',
  'deepseek-v3-0324': 'deepseek-v3-0324',
  'gemini-2-5-pro': 'gemini-25-pro',
  'gemini-2-5-flash': 'gemini-25-flash',
  'gemini-2-0-flash': 'gemini-20-flash',
  'gemini-2-0-flash-lite': 'gemini-20-flash-lite',
  'gemini-2-0-pro': 'gemini-20-pro',
  'gemini-3-pro': 'gemini-3-pro',
  'gemini-3-flash': 'gemini-3-flash',
  'gemini-3-1-pro': 'gemini-31-pro',
  'gemini-2-5-flash-lite-preview-09-2025': 'gemini-25-flash-lite-preview-09-2025',
  'grok-3': 'grok-3',
  'grok-4': 'grok-4',
  'grok-3-mini': 'grok-3-mini',
  'grok-4-1-fast': 'grok-41-fast',
  'grok-4-fast': 'grok-4-fast',
  'grok-code-fast-1': 'grok-code-fast-1',
  'llama-4-maverick': 'llama-4-maverick',
  'llama-4-scout': 'llama-4-scout',
  'mistral-medium-3': 'mistral-medium-3',
  'mistral-medium-3-1': 'mistral-medium-31',
  'mistral-large-3': 'mistral-large-3',
  'mistral-large-3-2512': 'mistral-large-3-2512',
  'mistral-small-3': 'mistral-small-3',
  'mistral-small-3-1-24b': 'mistral-small-31-24b',
  'mistral-small-3-2-24b': 'mistral-small-32-24b',
  'devstral-2': 'devstral-2',
  'devstral-small-2': 'devstral-2',
  'codestral-2508': 'codestral-2508',
  'qwen3-235b-a22b-instruct': 'qwen3-235b-a22b',
  'qwen3-235b-a22b': 'qwen3-235b-a22b',
  'qwen3-max': 'qwen3-max',
  'qwen3-max-thinking-preview': 'qwen3-max-thinking',
  'qwen-2-5-max': 'qwen25-max',
  'qwen3-30b-a3b': 'qwen3-30b-a3b',
  'qwen3-32b': 'qwen3-32b',
  'qwen3-14b': 'qwen3-14b',
  'qwen3-8b': 'qwen3-8b',
  'qwen3-coder-480b-a35b': 'qwen3-coder-480b-a35b',
  'qwen3-coder-flash': 'qwen3-coder-flash',
  'qwen3-coder-next': 'qwen3-coder-next',
  'qwen3-coder-plus': 'qwen3-coder-plus',
  'qwen-3-5-397b-a17b': 'qwen35-397b-a17b',
  'qwen-plus': 'qwen-plus',
  'glm-4-7': 'glm-47',
  'glm-4-6': 'glm-46',
  'glm-4-5': 'glm-45',
  'glm-5': 'glm-5',
  'kimi-k2': 'kimi-k2',
  'kimi-k2-0905': 'kimi-k25',
  'kimi-k2-thinking': 'kimi-k2-thinking',
  'minimax-m2-1': 'minimax-m21',
  'minimax-m2': 'minimax-m2',
  'minimax-m2-5': 'minimax-m25',
  'nvidia-nemotron-3-nano-30b-a3b': 'nvidia-nemotron-3',
  'nvidia-nemotron-nano-12b-v2-vl': 'nemotron-nano-12b-2-vl',
}

// From fetch-epoch.ts: MODEL_NAME_MAP
const EPOCH_MAPPINGS: Record<string, string> = {
  'Claude Opus 4.6': 'claude-opus-46',
  'Claude Opus 4.5': 'claude-opus-45',
  'Claude Opus 4.1': 'claude-opus-41',
  'Claude Opus 4': 'claude-opus-4',
  'Claude Sonnet 4.5': 'claude-sonnet-45',
  'Claude Sonnet 4': 'claude-sonnet-4',
  'Claude Haiku 4.5': 'claude-haiku-45',
  'Claude 3.7 Sonnet': 'claude-37-sonnet',
  'Claude 3.5 Sonnet (October 2024)': 'claude-35-sonnet',
  'Claude 3.5 Haiku': 'claude-35-haiku',
  'GPT-5.2': 'gpt-52',
  'GPT-5': 'gpt-5',
  'GPT-5.1': 'gpt-51',
  'GPT-4.1': 'gpt-41',
  'GPT-4.1 mini': 'gpt-41-mini',
  'GPT-4o (Nov 2024)': 'gpt-4o',
  'GPT-4o mini': 'gpt-4o-mini',
  'o3': 'o3',
  'o3-mini': 'o3-mini',
  'o4-mini': 'o4-mini',
  'o1': 'o1',
  'DeepSeek-R1': 'deepseek-r1',
  'DeepSeek-R1 (May 2025)': 'deepseek-r1-0528',
  'DeepSeek-V3': 'deepseek-v3',
  'DeepSeek-V3.1': 'deepseek-v31',
  'Gemini 2.5 Pro (Jun 2025)': 'gemini-25-pro',
  'Gemini 2.5 Flash (Jun 2025)': 'gemini-25-flash',
  'Gemini 2.0 Flash': 'gemini-20-flash',
  'Gemini 3 Pro': 'gemini-3-pro',
  'Gemini 3 Flash': 'gemini-3-flash',
  'Grok 3': 'grok-3',
  'Grok 4': 'grok-4',
  'Grok-3 mini': 'grok-3-mini',
  'Llama 4 Maverick': 'llama-4-maverick',
  'Llama 4 Scout': 'llama-4-scout',
  'Mistral Medium 3': 'mistral-medium-3',
  'Qwen3-235B-A22B': 'qwen3-235b',
  'Qwen3-Max': 'qwen3-max',
  'Qwen2.5-Max': 'qwen25-max',
  'GLM-4.7': 'glm-47',
  'Kimi K2': 'kimi-k2',
  'Kimi K2.5': 'kimi-k25',
  'Kimi K2 Thinking': 'kimi-k2-thinking',
  'DeepSeek-V3.2': 'deepseek-v32',
  'DeepSeek-V3.2-Exp': 'deepseek-v32-exp',
  'DeepSeek-V3 (Mar 2025)': 'deepseek-v3-0325',
  'GPT-4.1 nano': 'gpt-41-nano',
  'GPT-4.5': 'gpt-45',
  'GPT-5 Pro': 'gpt-5-pro',
  'GPT-5 mini': 'gpt-5-mini',
  'GPT-5 nano': 'gpt-5-nano',
  'o1-mini': 'o1-mini',
  'o1-preview': 'o1-preview',
  'o3-pro': 'o3-pro',
  'Gemini 2.0 Flash Thinking (Jan 2025)': 'gemini-20-flash-thinking',
  'Gemini 2.0 Pro': 'gemini-20-pro',
  'Gemini 2.5 Pro (Mar 2025)': 'gemini-25-pro-0325',
  'Gemini 2.5 Pro (May 2025)': 'gemini-25-pro-0525',
  'Gemini 2.5 Flash (Apr 2025)': 'gemini-25-flash-0425',
  'Gemini 2.5 Flash (May 2025)': 'gemini-25-flash-0525',
  'Gemini 2.5 Flash (Sep 2025)': 'gemini-25-flash-0925',
  'Mistral Large': 'mistral-large',
  'Mistral Large 2': 'mistral-large-2',
  'Qwen3-235B-A22B-Thinking (Jul 2025)': 'qwen3-235b-thinking',
  'Qwen3-Coder-480B-A35B': 'qwen3-coder-480b',
  'Qwen Plus': 'qwen-plus',
  'Llama 3.3 70B': 'llama-33-70b',
  'Llama 3.2 90B': 'llama-32-90b',
  'Grok-2': 'grok-2',
  'Claude Sonnet 4.6': 'claude-sonnet-46',
  'GPT-5.2 Codex': 'gpt-52-codex',
  'GPT-5.2 Pro': 'gpt-52-pro',
  'GPT-5.1 Codex Mini': 'gpt-51-codex-mini',
  'Grok 4.1': 'grok-41',
  'Grok 4.1 Fast': 'grok-41-fast',
  'GLM-4.7 Flash': 'glm-47-flash',
  'GLM-5': 'glm-5',
  'MiniMax-M21': 'minimax-m21',
  'MiniMax-M25': 'minimax-m25',
  'MiniMax M2.1': 'minimax-m21',
  'MiniMax M2.5': 'minimax-m25',
  'Nvidia Nemotron 3': 'nvidia-nemotron-3',
  'Nemotron 3': 'nvidia-nemotron-3',
  'Qwen3.5-397B': 'qwen35-397b',
  'Qwen3.5 Plus': 'qwen35-plus',
  'Qwen3-Max-Thinking': 'qwen3-max-thinking',
  'Qwen3-Coder-Next': 'qwen3-coder-next',
  'Mistral Large 3': 'mistral-large-3',
  'Devstral 2': 'devstral-2',
  'DeepSeek-V3.2-Speciale': 'deepseek-v32-speciale',
  'Gemini 3.1 Pro': 'gemini-31-pro',
}

// From fetch-benchmarks.ts: LMARENA_MODEL_MAP
const LMARENA_MAPPINGS: Record<string, string> = {
  'claude-3-5-sonnet-20241022': 'claude-35-sonnet',
  'claude-3-5-haiku-20241022': 'claude-35-haiku',
  'claude-3.7-sonnet': 'claude-37-sonnet',
  'claude-3-7-sonnet': 'claude-37-sonnet',
  'claude-sonnet-4': 'claude-sonnet-4',
  'claude-sonnet-4-5': 'claude-sonnet-45',
  'claude-sonnet-4.5': 'claude-sonnet-45',
  'claude-sonnet-4-6': 'claude-sonnet-46',
  'claude-sonnet-4.6': 'claude-sonnet-46',
  'claude-opus-4': 'claude-opus-4',
  'claude-opus-4-1': 'claude-opus-41',
  'claude-opus-4.1': 'claude-opus-41',
  'claude-opus-4-5': 'claude-opus-45',
  'claude-opus-4.5': 'claude-opus-45',
  'claude-opus-4-6': 'claude-opus-46',
  'claude-opus-4.6': 'claude-opus-46',
  'claude-haiku-4-5': 'claude-haiku-45',
  'claude-haiku-4.5': 'claude-haiku-45',
  'gpt-4o-2024-11-20': 'gpt-4o',
  'gpt-4o': 'gpt-4o',
  'gpt-4o-mini': 'gpt-4o-mini',
  'gpt-4.1': 'gpt-41',
  'gpt-4-1': 'gpt-41',
  'gpt-4.1-mini': 'gpt-41-mini',
  'gpt-4-1-mini': 'gpt-41-mini',
  'gpt-4.1-nano': 'gpt-41-nano',
  'gpt-4-1-nano': 'gpt-41-nano',
  'gpt-4.5': 'gpt-45',
  'gpt-4-5': 'gpt-45',
  'gpt-5': 'gpt-5',
  'gpt-5-mini': 'gpt-5-mini',
  'gpt-5-nano': 'gpt-5-nano',
  'gpt-5-pro': 'gpt-5-pro',
  'gpt-5.1': 'gpt-51',
  'gpt-5-1': 'gpt-51',
  'gpt-5.2': 'gpt-52',
  'gpt-5-2': 'gpt-52',
  'gpt-5.2-codex': 'gpt-52-codex',
  'gpt-5-2-codex': 'gpt-52-codex',
  'gpt-5.2-pro': 'gpt-52-pro',
  'gpt-5-2-pro': 'gpt-52-pro',
  'gpt-5.1-codex-mini': 'gpt-51-codex-mini',
  'gpt-5-1-codex-mini': 'gpt-51-codex-mini',
  'o1': 'o1',
  'o1-mini': 'o1-mini',
  'o1-preview': 'o1-preview',
  'o3': 'o3',
  'o3-mini': 'o3-mini',
  'o3-pro': 'o3-pro',
  'o4-mini': 'o4-mini',
  'deepseek-r1': 'deepseek-r1',
  'deepseek-v3': 'deepseek-v3',
  'deepseek-v3-0325': 'deepseek-v3-0325',
  'deepseek-v3.1': 'deepseek-v31',
  'deepseek-v3.2': 'deepseek-v32',
  'gemini-2.0-flash': 'gemini-20-flash',
  'gemini-2-0-flash': 'gemini-20-flash',
  'gemini-2.5-pro': 'gemini-25-pro',
  'gemini-2-5-pro': 'gemini-25-pro',
  'gemini-2.5-flash': 'gemini-25-flash',
  'gemini-2-5-flash': 'gemini-25-flash',
  'gemini-3-pro': 'gemini-3-pro',
  'gemini-3-flash': 'gemini-3-flash',
  'gemini-3.1-pro': 'gemini-31-pro',
  'gemini-3-1-pro': 'gemini-31-pro',
  'grok-3': 'grok-3',
  'grok-3-mini': 'grok-3-mini',
  'grok-4': 'grok-4',
  'grok-4.1': 'grok-41',
  'grok-4-1': 'grok-41',
  'grok-4.1-fast': 'grok-41-fast',
  'grok-4-1-fast': 'grok-41-fast',
  'llama-4-maverick': 'llama-4-maverick',
  'llama-4-scout': 'llama-4-scout',
  'mistral-medium-3': 'mistral-medium-3',
  'mistral-large-3': 'mistral-large-3',
  'qwen3-235b': 'qwen3-235b',
  'qwen3-max': 'qwen3-max',
  'qwen2.5-max': 'qwen25-max',
  'qwen-2-5-max': 'qwen25-max',
  'glm-4.7': 'glm-47',
  'glm-4-7': 'glm-47',
  'glm-4.7-flash': 'glm-47-flash',
  'glm-4-7-flash': 'glm-47-flash',
  'glm-5': 'glm-5',
  'kimi-k2': 'kimi-k2',
  'kimi-k2.5': 'kimi-k25',
  'kimi-k2-5': 'kimi-k25',
  'kimi-k2-thinking': 'kimi-k2-thinking',
  'minimax-m21': 'minimax-m21',
  'minimax-m2-1': 'minimax-m21',
  'minimax-m25': 'minimax-m25',
  'minimax-m2-5': 'minimax-m25',
  'nvidia-nemotron-3': 'nvidia-nemotron-3',
  'nemotron-3': 'nvidia-nemotron-3',
  'devstral-2': 'devstral-2',
  'qwen3.5-397b': 'qwen35-397b',
  'qwen3-5-397b': 'qwen35-397b',
  'qwen35-397b': 'qwen35-397b',
  'qwen3.5-plus': 'qwen35-plus',
  'qwen3-5-plus': 'qwen35-plus',
  'qwen35-plus': 'qwen35-plus',
  'qwen3-coder-next': 'qwen3-coder-next',
  'qwen3-max-thinking': 'qwen3-max-thinking',
  'deepseek-v3.2-speciale': 'deepseek-v32-speciale',
  'deepseek-v32-speciale': 'deepseek-v32-speciale',
}

async function main() {
  console.log('Importing hardcoded model name mappings to DB...')

  const allMappings: { source_key: string; source_name: string; model_slug: string; confidence: string; auto_generated: boolean }[] = []

  for (const [sourceName, slug] of Object.entries(AA_MAPPINGS)) {
    allMappings.push({
      source_key: 'artificial_analysis',
      source_name: sourceName,
      model_slug: slug,
      confidence: 'exact',
      auto_generated: false,
    })
  }

  for (const [sourceName, slug] of Object.entries(EPOCH_MAPPINGS)) {
    allMappings.push({
      source_key: 'epoch_ai',
      source_name: sourceName,
      model_slug: slug,
      confidence: 'exact',
      auto_generated: false,
    })
  }

  for (const [sourceName, slug] of Object.entries(LMARENA_MAPPINGS)) {
    allMappings.push({
      source_key: 'lmarena',
      source_name: sourceName,
      model_slug: slug,
      confidence: 'exact',
      auto_generated: false,
    })
  }

  console.log(`  Total mappings: ${allMappings.length} (AA: ${Object.keys(AA_MAPPINGS).length}, Epoch: ${Object.keys(EPOCH_MAPPINGS).length}, LMArena: ${Object.keys(LMARENA_MAPPINGS).length})`)

  // Upsert in batches of 50
  let inserted = 0
  for (let i = 0; i < allMappings.length; i += 50) {
    const batch = allMappings.slice(i, i + 50)
    const { error } = await supabase
      .from('model_name_mappings')
      .upsert(batch, { onConflict: 'source_key,source_name' })
    if (error) {
      console.error(`  Batch ${i}-${i + batch.length} failed:`, error.message)
    } else {
      inserted += batch.length
    }
  }

  console.log(`Imported ${inserted}/${allMappings.length} mappings to DB`)
}

main().catch((err) => {
  console.error('Import failed:', err instanceof Error ? err.message : String(err))
  process.exit(1)
})
